name: Testing The Cpp Code

on:
  push:
    branches: ["Tensor/**", "main"]
  pull_request:
    branches: ["main", "Tensor/**"]

jobs:
  run-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'operatorOverloading'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.18.0
        with:
          clang-format-version: '18'
          check-path: ${{ matrix.path }}
          fallback-style: 'LLVM' # optional

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm
          vcvarsall: true
          cmake: "3.28.3"
          ninja: true
          vcpkg: true


      - name: Testing The cmake
        run: |
          echo "Testing CMake build..."
          cd 'Copy and Move'
          mkdir build
          cd build
          cmake -S .. -B . -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          ./olas

