name: Testing The Cpp Code

on:
  push:
    branches: ["Tensor/**", "main"]
  pull_request:
    branches: ["main", "Tensor/**"]

jobs:
  run-and-test:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm
          vcvarsall: true
          cmake: true
          ninja: true
          vcpkg: true

      - name: Test formatting
        run: |
         find . \( -name "*.hpp" -o -name "*.cpp" \) -exec clang-format --dry-run --Werror {} +

      - name: Testing The cmake
        run: |
          echo "Testing CMake build..."
          mkdir build
          cd build
          cmake --S ../'Copy and Move'/CMakelists.txt -B . -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          cmake --build .

